# Generated by Django 4.0.5 on 2022-06-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_fantasy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=40)),
                ('pub_date', models.DateField(max_length=30)),
                ('Author', models.CharField(max_length=30)),
            ],
        ),
    ]
