# Generated by Django 4.0.5 on 2022-06-16 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_adventure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.author'),
        ),
    ]
