# Generated by Django 4.0.5 on 2022-06-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_adventure_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
