# Generated by Django 4.0.5 on 2022-06-27 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_adventure_pub_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adventure',
            new_name='The_lord_of_rings',
        ),
    ]
