# Generated by Django 4.0.5 on 2022-06-27 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_rename_adventure_the_lord_of_rings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fantasy',
            new_name='Harry_Potter',
        ),
    ]
