# Generated by Django 4.0.5 on 2022-06-27 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_rename_the_lord_of_rings_the_chronicles_of_narnia_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='The_Chronicles_of_Narnia',
        ),
    ]
