# Generated by Django 4.0.5 on 2022-06-27 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_the_chronicles_of_narnia_title_star_wars'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Star_Wars',
            new_name='Star_War',
        ),
    ]
