# Generated by Django 4.0.5 on 2022-06-27 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_rename_star_wars_star_war'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hunger_Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=65)),
                ('pub_date', models.DateField(verbose_name=' date published')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.author')),
            ],
        ),
    ]
