# Generated by Django 4.0.5 on 2022-06-27 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_hunger_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
