# Generated by Django 4.1 on 2022-08-30 16:22

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0018_delete_choice_delete_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", tinymce.models.HTMLField(blank=True, default="")),
                ("notes", tinymce.models.HTMLField(blank=True, default="")),
            ],
        ),
    ]
